### ISSUE TITLE
mincbeast segmentation fault with newer gcc

### ISSUE THREAD

**Issue by stilley2** [BIC-MNI/BEaST#10]
When compiling with 9.1.1 (Fedora) the tests fail with a segmentation fault. This does not occur with older versions of gcc (4.8.5 Centos7). It also does not occur when compiling in debug mode. I started doing some digging, and I believe the error occurs during argument parsing, due to [this issue](https://stackoverflow.com/questions/13690306/conversion-from-string-literal-to-char-is-deprecated).

**Comment by gdevenyi** [comment]
Can you build RelWithDebug and get a stacktrace with gdb?

**Comment by vfonov** [comment]
strange, I build minc-toolkit-v2 for ubuntu 18.04 , it uses gcc 7.4 - seem to be working fine.

**Comment by stilley2** [comment]
I can't build it with RelWithDebug. I get the error

    No rule to make target '/home/stilley2/lib/minc/minc_build_rwd/external/opt/minc/1.9.17/lib/libhdf5_debug.a', needed by 'mincbeast'.  Stop.

Even though I'm not using the system hdf5. The script I'm using to build is below.

```bash
#!/bin/bash

set -e
set -u

git clone --recursive --branch release-1.9.17 https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2_src_rwd
mkdir minc_build_rwd
pushd minc_build_rwd
cmake ../minc-toolkit-v2_src_rwd \
-DCMAKE_BUILD_TYPE:STRING=RelWithDebug \
-DCMAKE_INSTALL_PREFIX:PATH=/opt/minc/1.9.17 \
-DMT_BUILD_ABC:BOOL=OFF \
-DMT_BUILD_ANTS:BOOL=OFF \
-DMT_BUILD_C3D:BOOL=OFF \
-DMT_BUILD_ELASTIX:BOOL=OFF \
-DMT_BUILD_IM:BOOL=OFF \
-DMT_BUILD_ITK_TOOLS:BOOL=OFF \
-DMT_BUILD_LITE:BOOL=OFF \
-DMT_BUILD_OPENBLAS:BOOL=ON \
-DMT_BUILD_QUIET:BOOL=OFF \
-DMT_BUILD_SHARED_LIBS:BOOL=OFF \
-DMT_BUILD_VISUAL_TOOLS:BOOL=OFF \
-DMT_USE_OPENMP:BOOL=ON \
-DUSE_SYSTEM_FFTW3D:BOOL=OFF \
-DUSE_SYSTEM_FFTW3F:BOOL=OFF \
-DUSE_SYSTEM_GLUT:BOOL=OFF \
-DUSE_SYSTEM_GSL:BOOL=OFF \
-DUSE_SYSTEM_HDF5:BOOL=OFF \
-DUSE_SYSTEM_ITK:BOOL=OFF \
-DUSE_SYSTEM_NETCDF:BOOL=OFF \
-DUSE_SYSTEM_NIFTI:BOOL=OFF \
-DUSE_SYSTEM_PCRE:BOOL=OFF \
-DUSE_SYSTEM_ZLIB:BOOL=OFF \
-DBUILD_TESTING=ON
make
# make test
popd
```

**Comment by gdevenyi** [comment]
Sorry should be RelWithDebInfo

**Comment by stilley2** [comment]
Here's the backtrace from gdb:

```
#0  0x000000000043a9f4 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#1  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#2  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#3  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#4  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#5  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#6  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#7  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#8  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#9  0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#10 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#11 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#12 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#13 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#14 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#15 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#16 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#17 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#18 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#19 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#20 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#21 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#22 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#23 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#24 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
#25 0x000000000043a9f9 in get_arguments (argc=<optimized out>, argv=0x7fffffffd4b8, _options=0x7fffffffd2e0)
    at /home/stilley2/lib/minc/minc-toolkit-v2_src_rwd/BEaST/beast_config.cpp:115
```

**Comment by stilley2** [comment]
Hmm apparently that's not the complete stack trace. I ran it without the pager and it just kept repeating that line

**Comment by christiantinauer** [comment]
I have the same problem on my Arch Linux machine. Compiling the minc toolkit with the current gcc version (8.3.0) causes segfaults in BEaST. When I recompiled with gcc-7 (7.4.1) it worked again. Build was done in Release mode.

**Comment by vfonov** [comment]
Latest fixes seem to have resolved this issue.
